name: docker_news
networks:
  dev:

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5411:5432"
    env_file:
      - .env-non-dev
    volumes:
      - .postgres:/var/lib/postgres/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 5s
      timeout: 10s
      retries: 5
    # restart: unless-stopped

  app:
     container_name: my_app
     build:
       context: .
     depends_on:
       db:
         condition: service_healthy
     command:  ["sh", "-c", "alembic upgrade head && gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"]
     ports:
       - 9999:8000
     restart: always
     env_file:
       - .env-non-dev


  nginx:
    image: nginx:stable-alpine
    ports:
      - "32:80"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - app
    networks:
      - dev




#  redis:
#    image: redis:7
#    container_name: redis_news
#    command: --port 5370
#    expose:
#      - 5370
#    env_file:
#      - .env-non-dev




#  celery:
#    build:
#      context: .
#    env_file:
#      - .env-non-dev
#    container_name: celery_app
#    command: ["/test_app/docker/celery.sh", "celery"]
#    depends_on:
#      - redis
#
#  flower:
#    build:
#      context: .
#    env_file:
#      - .env-non-dev
#    container_name: flower_app
#    command: ["/test_app/docker/celery.sh", "flower"]
#    depends_on:
#      - redis
#      - celery
#    ports:
#      - 8888:5555